### ISSUE TITLE
Use API keys instead of Username/Password for Nessus

### ISSUE THREAD

**Issue by Psynbiotik** [HASecuritySolutions/VulnWhisperer#96]
Nessus in the new version only supports a single user, having the option to use API keys to access Nessus API will give users of Nessus greater control over access.

Examples for using the api keys instead of the logged in session.
https://community.tenable.com/s/article/Example-API-calls-to-gather-information-on-more-than-200-agents-at-a-time-and-delete-offline-agents

**Comment by greengeek** [comment]
Dang, I wrote a request for this and changed the title a little and saw this post had already been created.  Instead of submitting a new request I will just add my write up to this one.  Sorry for the redundancy.

**Describe the bug**
Since Nessus Professional 7.x (we are now on 8.2.3) tenable has removed the ability to have multiusers. There is now only one user and that user has full administration rights.  It would be best not to expose the information of this user in the configs/frameworks_example.ini file for security issues.  A better solution would be to use the user generated keys (accessKey and secretKey) for authentication instead of using the older way of generating the token based on the username and password.  The api keys can be regenerated easily where as changing the user not so much.  This Nessus REST API is available in 6.4 and greater. https://docs.tenable.com/nessus/6_5/Content/UserProfileAPIKey.htm

**Affected module**
Nessus

**To Reproduce**
Login to Nessus Home (free for noncommerical use) or Nessus Professional (commerical).  At the top right click on your username and then My Account.  Click on the API Keys tab.  There you can click on the "Generate" button to generate the keys.  More information can be found at https://[NESSUS_SERVER_ADDRESS]:8834/api#/authorization

**Expected behavior**
The ability to login without having to provide a username and password.

**System in which VulnWhisperer runs (please complete the following information):**
Can be used with all operating systems. 

**Additional context**
I created an example to authenticate and pull down scan information via the keys found here, https://github.com/greengeek/nessus-api/blob/master/nessus-scan.py

**Comment by reactor7171** [comment]
Issue solved in #176, already merged with master branch and added to the development branch as well.

**Comment by b4cktr4ck2** [comment]
I noticed that in the frameworks_example.ini file the fields for Nessus/Tenable.io credentials are still present. Can these fields please be removed, OR can there be a clear indication that these credentials sets are not needed since the API keys from Nessus/Tenable.io are what's needed to access the scan data?

**Comment by pemontto** [comment]
@kozlovsas you can use either username/password, API keys, or both (but it will VulnWhisperer will preference API keys). I see how this could be confusing, but probably something best explained in the documentation, that one or the other can be used.

**Comment by b4cktr4ck2** [comment]
Thanks for the info @pemontto ! I agree that documentation might be the best place to state this.
